# Generated by Django 4.2.28 on 2026-02-24 06:38

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialWorker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Имя может содержать только буквы', regex='^[А-Яа-яЁёA-Za-z\\s]+$')], verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Фамилия может содержать только буквы', regex='^[А-Яа-яЁёA-Za-z\\s]+$')], verbose_name='Фамилия')),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.RegexValidator(message='Отчество может содержать только буквы', regex='^[А-Яа-яЁёA-Za-z\\s]+$')], verbose_name='Отчество')),
                ('phone', models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Номер телефона должен быть в формате: '+999999999'. До 15 цифр.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Адрес')),
                ('position', models.CharField(choices=[('worker', 'Социальный работник'), ('senior', 'Старший социальный работник'), ('supervisor', 'Руководитель'), ('specialist', 'Специалист')], default='worker', max_length=50, verbose_name='Должность')),
                ('status', models.CharField(choices=[('active', 'Активный'), ('inactive', 'Неактивный'), ('vacation', 'В отпуске'), ('sick', 'На больничном')], default='active', max_length=20, verbose_name='Статус')),
                ('employee_id', models.CharField(help_text='Уникальный идентификатор работника', max_length=50, unique=True, verbose_name='Табельный номер')),
                ('hire_date', models.DateField(blank=True, null=True, verbose_name='Дата приема на работу')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='social_worker', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Социальный работник',
                'verbose_name_plural': 'Социальные работники',
                'ordering': ['last_name', 'first_name'],
                'indexes': [models.Index(fields=['last_name', 'first_name'], name='accounts_so_last_na_1cd185_idx'), models.Index(fields=['status'], name='accounts_so_status_f158f3_idx'), models.Index(fields=['employee_id'], name='accounts_so_employe_db87a7_idx')],
            },
        ),
    ]
