# Generated by Django 4.2.28 on 2026-04-08 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_servicelocation_servicerecipient_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlannedVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField(verbose_name='Дата визита')),
                ('visit_time', models.TimeField(blank=True, null=True, verbose_name='Время')),
                ('notes', models.TextField(blank=True, verbose_name='Примечание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'recipient',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='planned_visits',
                        to='accounts.servicerecipient',
                        verbose_name='Подопечный',
                    ),
                ),
                (
                    'social_worker',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='planned_visits',
                        to='accounts.socialworker',
                        verbose_name='Социальный работник',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Запланированный визит',
                'verbose_name_plural': 'Запланированные визиты',
                'ordering': ['visit_date', 'visit_time', 'pk'],
                'unique_together': {('recipient', 'visit_date')},
            },
        ),
    ]
