# Generated by Django 4.2.28 on 2026-04-09 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_planned_visit'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitTaskReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_date', models.DateField(verbose_name='Дата выполнения задачи')),
                ('description', models.TextField(blank=True, verbose_name='Описание задачи')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'recipient',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='visit_task_reminders',
                        to='accounts.servicerecipient',
                        verbose_name='Подопечный',
                    ),
                ),
                (
                    'social_worker',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='visit_task_reminders',
                        to='accounts.socialworker',
                        verbose_name='Социальный работник',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Напоминание о задаче',
                'verbose_name_plural': 'Напоминания о задачах',
                'ordering': ['task_date', 'social_worker__last_name', 'pk'],
            },
        ),
    ]
