# Generated by Django 4.2.28 on 2026-04-13 10:58

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_safetybriefingrecord_passed'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkloadRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('housing_type', models.CharField(choices=[('house', 'Дом'), ('apartment', 'Квартира')], default='apartment', max_length=20, verbose_name='Тип (дом или квартира)')),
                ('period_year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)], verbose_name='Год')),
                ('period_month', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Месяц')),
                ('visits_per_week', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6, verbose_name='Кратность посещений (раз в неделю)')),
                ('visits_per_month', models.DecimalField(blank=True, decimal_places=2, help_text='Если не указано — рассчитывается из кратности за неделю (× 52/12).', max_digits=8, null=True, verbose_name='Кратность посещений (раз в месяц)')),
                ('visit_duration_minutes', models.PositiveIntegerField(default=0, verbose_name='Время посещений (минут)')),
                ('worked_minutes_month', models.PositiveIntegerField(default=0, verbose_name='Время отработано за месяц (минут)')),
                ('worked_hours_month', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Время отработано за месяц (часов)')),
                ('work_time_norm_minutes', models.PositiveIntegerField(default=9600, help_text='По умолчанию 9600 мин (160 ч).', verbose_name='Норма рабочего времени (минут в месяц)')),
                ('load_coefficient', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=8, verbose_name='Коэффициент нагрузки')),
                ('rate', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=4, verbose_name='Ставка')),
                ('notes', models.TextField(blank=True, verbose_name='Примечание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workload_records', to='accounts.servicelocation', verbose_name='Населённый пункт')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workload_records', to='accounts.servicerecipient', verbose_name='Подопечный')),
                ('social_worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workload_records', to='accounts.socialworker', verbose_name='Работник')),
            ],
            options={
                'verbose_name': 'Запись учёта нагрузки',
                'verbose_name_plural': 'Учёт нагрузки',
                'ordering': ['-period_year', '-period_month', 'social_worker__last_name', 'pk'],
            },
        ),
        migrations.AddIndex(
            model_name='workloadrecord',
            index=models.Index(fields=['period_year', 'period_month'], name='accounts_wo_period__2a4c48_idx'),
        ),
        migrations.AddIndex(
            model_name='workloadrecord',
            index=models.Index(fields=['social_worker', 'period_year', 'period_month'], name='accounts_wo_social__5e130a_idx'),
        ),
    ]
