# Generated by Django 4.2.28 on 2026-04-13 11:08

from django.db import migrations, models


def _recompute_workloads(apps, schema_editor):
    from accounts.models import WorkloadRecord
    for wr in WorkloadRecord.objects.all():
        if wr.work_time_norm_minutes == 9600:
            wr.work_time_norm_minutes = 10080
        wr.save()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_workload_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workloadrecord',
            name='visit_duration_minutes',
            field=models.PositiveIntegerField(default=0, verbose_name='Время 1 посещения (минут)'),
        ),
        migrations.AlterField(
            model_name='workloadrecord',
            name='visits_per_month',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Если не указано — считается как кратность за неделю × 4 (как в типовой таблице нагрузки).', max_digits=8, null=True, verbose_name='Кратность посещений (раз в месяц)'),
        ),
        migrations.AlterField(
            model_name='workloadrecord',
            name='work_time_norm_minutes',
            field=models.PositiveIntegerField(default=10080, help_text='По умолчанию 10080 мин (168 ч в месяц), как в расчётных таблицах нагрузки.', verbose_name='Норма рабочего времени (минут в месяц)'),
        ),
        migrations.RunPython(_recompute_workloads, migrations.RunPython.noop),
    ]
