# Generated by Django 4.2.28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('accounts', '0016_recompute_workload_load_coef'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(
                    blank=True,
                    help_text='Необязательно. JPG, PNG или WebP, до 2 МБ.',
                    null=True,
                    upload_to='profiles/%Y/%m/',
                    verbose_name='Фото профиля',
                )),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'user',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='socworker_profile',
                        to='auth.User',
                        verbose_name='Пользователь',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
            },
        ),
    ]
