# Generated by Django 4.2.28 on 2026-04-15 12:37

import accounts.belarus_phone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_user_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerecipient',
            name='phone',
            field=models.CharField(
                blank=True,
                help_text='Формат: +375 (XX) XXX-XX-XX',
                max_length=22,
                null=True,
                validators=[accounts.belarus_phone.validate_belarus_phone_optional],
                verbose_name='Телефон',
            ),
        ),
        migrations.AlterField(
            model_name='socialworker',
            name='phone',
            field=models.CharField(
                blank=True,
                help_text='Формат: +375 (XX) XXX-XX-XX',
                max_length=22,
                null=True,
                validators=[accounts.belarus_phone.validate_belarus_phone_optional],
                verbose_name='Телефон',
            ),
        ),
    ]
