# Generated by Django 4.2.28 on 2026-04-15 12:38
#
# Индексы в MySQL уже могут иметь длинные имена (как в Django 4.2+); RenameIndex
# падает, если старого имени нет. Обновляем только state; на схему — безопасные AlterField.

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_belarus_phone_fields'),
    ]

    _rename_and_alter_state = [
        migrations.RenameIndex(
            model_name='servicerecipient',
            new_name='accounts_se_employe_b86ce8_idx',
            old_name='accounts_se_employe_idx',
        ),
        migrations.RenameIndex(
            model_name='servicerecipient',
            new_name='accounts_se_last_na_28a210_idx',
            old_name='accounts_se_last_na_idx',
        ),
        migrations.RenameIndex(
            model_name='servicerecipient',
            new_name='accounts_se_disabil_c77471_idx',
            old_name='accounts_se_disabil_idx',
        ),
        migrations.RenameIndex(
            model_name='servicerecipient',
            new_name='accounts_se_social__285d51_idx',
            old_name='accounts_se_social__idx',
        ),
        migrations.AlterField(
            model_name='servicelocation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='workloadrecord',
            name='location',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='workload_records',
                to='accounts.servicelocation',
            ),
        ),
        migrations.AlterField(
            model_name='workloadrecord',
            name='recipient',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='workload_records',
                to='accounts.servicerecipient',
            ),
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=_rename_and_alter_state,
            database_operations=[
                migrations.AlterField(
                    model_name='servicelocation',
                    name='id',
                    field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
                ),
                migrations.AlterField(
                    model_name='workloadrecord',
                    name='location',
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='workload_records',
                        to='accounts.servicelocation',
                    ),
                ),
                migrations.AlterField(
                    model_name='workloadrecord',
                    name='recipient',
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='workload_records',
                        to='accounts.servicerecipient',
                    ),
                ),
            ],
        ),
    ]
