# Generated by Django 4.2.28 on 2026-04-23 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_servicerecipient_housing_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerecipient',
            name='housing_type',
            field=models.CharField(choices=[('house', 'Дом'), ('apartment', 'Квартира')], default='apartment', help_text='В «Расчёте нагрузки» сначала подставляется по тексту в «Адрес», иначе это поле.', max_length=20, verbose_name='Тип жилья (дом / квартира)'),
        ),
    ]
