# Generated by Django 4.2.28 on 2026-05-10 11:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0025_userprofile_admin_panel_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='admin_portal_password_plaintext',
            field=models.CharField(blank=True, default='', help_text='Обновляется при создании пользователя, смене пароля из панели или из формы «Смена пароля».', max_length=256, verbose_name='Пароль для панели администратора'),
        ),
        migrations.CreateModel(
            name='AdminPortalPasswordChangeNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('role_label', models.CharField(max_length=120)),
                ('new_password_plaintext', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dismissed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_portal_password_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Уведомление: смена пароля',
                'verbose_name_plural': 'Уведомления: смены пароля',
                'ordering': ('-created_at',),
            },
        ),
    ]
