# Generated by Django 4.2.28 on 2026-05-10 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_admin_portal_password_plaintext_and_notifications'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortalAuthenticationCodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_code_override', models.CharField(blank=True, default='', help_text='Пустое значение — берётся из настроек окружения INVENTORY_AUTHENTICATION_CODE.', max_length=512, verbose_name='Код раздела «Инвентаризация»')),
                ('admin_panel_code_override', models.CharField(blank=True, default='', help_text='Пустое значение — берётся из настроек ADMIN_PANEL_AUTHENTICATION_CODE.', max_length=512, verbose_name='Код панели администратора')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Секретные коды порталов',
                'verbose_name_plural': 'Секретные коды порталов',
            },
        ),
    ]
