# Generated by Django 4.2.28 on 2026-04-13 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название отделения')),
                ('head', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_inventory_departments', to='auth.User', verbose_name='Руководитель отделения')),
            ],
            options={
                'verbose_name': 'Отделение',
                'verbose_name_plural': 'Отделения',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InventoryUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_number', models.CharField(max_length=64, unique=True, verbose_name='Инвентарный номер')),
                ('name', models.CharField(max_length=500, verbose_name='Название')),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Стоимость')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('responsible', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_units', to='auth.User', verbose_name='Ответственный')),
            ],
            options={
                'verbose_name': 'Единица учёта',
                'verbose_name_plural': 'Единицы учёта',
                'ordering': ['inventory_number'],
            },
        ),
        migrations.CreateModel(
            name='InventoryProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('position', models.CharField(blank=True, max_length=255, verbose_name='Должность')),
                ('role', models.CharField(choices=[('employee', 'Сотрудник'), ('department_head', 'Руководитель отдела'), ('warehouse_keeper', 'Завхоз')], default='employee', max_length=30, verbose_name='Роль')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='Телефон')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_profiles', to='inventory.department', verbose_name='Отделение')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_profile', to='auth.User', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль инвентаризации',
                'verbose_name_plural': 'Профили инвентаризации (пользователи)',
                'ordering': ['full_name'],
            },
        ),
    ]
