# Generated by Django 4.2.28 on 2026-04-15 12:38

import accounts.belarus_phone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryprofile',
            name='phone',
            field=models.CharField(blank=True, help_text='Формат: +375 (XX) XXX-XX-XX', max_length=40, validators=[accounts.belarus_phone.validate_belarus_phone_optional], verbose_name='Телефон'),
        ),
    ]
